feat: t5 - get all unique extensions of files
rtest12/devops-camp-2023 pull request #5
Opened 2023-04-02 17:55 UTC by rtest12

https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter2%20-%20bash%20basics/l2/bash%20expansion.md#t5---get-all-unique-extensions-of-files

## t5 - get all unique extensions of files

Script should get a folder as an argument and return a list of unique extensions of all files (including in the nested directories)

name the file: `chapter2-l2-t5-get-file-unique-extensions.sh`

example of the call:

`./chapter2-l2-t5-get-file-unique-extensions.sh ~/tmp/bazel`
```
c
h
zip
```
## My output:
```
✦13 ➜ ./chapter2-l2-t5-get-file-unique-extensions.sh /home/maxim/test
pem
pub
sh
t4
txt
yaml

```

2023-04-05 08:29 UTC, kseniyashaydurova requested changes

2023-04-05 08:29 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +err() {
Please make `err` function in the same way I asked you in previous PRs, i.e. add `[ERROR]` prefix and make `exit` from it

2023-04-05 08:29 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +
something works incorrectly here
![image](https://user-images.githubusercontent.com/26448672/230025603-5283020f-64bc-41f7-b0b6-36592d78639b.png)

2023-04-05 08:29 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  echo ${list##*.}
always quote strings passed to `echo`

2023-04-05 08:29 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +for file in $files; do
Let's follow style guide `${files}`

2023-04-05 08:29 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  list=${file##*/}
let's add info that it is local var

2023-04-07 20:59 UTC, rtest12 commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +
fixed

2023-04-13 02:33 UTC, kseniyashaydurova approved these changes

2023-04-13 02:33 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  list=${file##*/}
It is a bad practice to call vars as vars types, i.e. list / map / string and etc. Please find more appropriate name for it

2023-04-13 02:33 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#
```suggestion

```

2023-04-13 02:33 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +done | sort -u
Pls add one empty line at the end

2023-04-25 19:37 UTC, merged